### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by katarinabrilej** [jasapozne/APPR-2020-21#1]
Pri imenih stolpcev se raje izogibaj presledkov, nadomesti jih recimo s podčrtaji. Prav tako naj v imenih stolpcev ne bo šumnikov.

Pri funkciji `uvazanje` je bolje, če nastaviš kodiranje UTF-8, saj se bodo tako posebne črke pravilno uvozile (in ne bo "čudnih" znakov, recimo pri Sao Tome and Principe in Curacao). Meni se uvoz v Binderju sedaj celo ne prevede.

```
locale=locale(encoding="UTF-8")
```

Ko dostopaš do stolpca lahko preprosteje uporabiš kar `$`:
```
uvoz$drzava <- uvoz.1
```
namesto
```
uvoz[["drzava"]] <- uvoz.1
```

1. in 2. tabela se uvozita na podoben način. Zato bo preproteje, če napišeš funkcijo, ki kot argument sprejme ime csv datoteke in jo potem uporabiš za obe tabeli:

```
uvozi <- function(ime_datoteke){
  ime <- paste0("podatki/",ime_datoteke, ".csv")
  uvoz <-read_csv(ime, locale=locale(encoding="UTF-8"),skip = 6, col_names=TRUE) %>% select(-1) %>% 
    pivot_longer(c(-1), names_to="leto",values_to="kolicina_MIO_$",values_drop_na=TRUE) %>%
    mutate(leto=parse_number(leto)) %>% rename(drzava=X2)  

  uvoz.1 <-uvoz$drzava %>% str_remove("\\.|,|:[A-Za-z ]*") %>%
    str_remove("Rep. [a-zA-Z .]*") %>%str_remove("Rep") %>%
    str_replace("São Tomé and Príncipe Dem\\. ", "Sao Tome and Principe") %>%
    str_replace("Côte d'Ivoire","Ivory Coast") %>% 
    str_replace("Curaçao Kingdom of the Netherlands","Curacao")

uvoz$drzava <- uvoz.1
return(uvoz)
}
uvoz.vseh.drzav <- uvozi("Uvoz")
izvoz.vseh.drzav <- uvozi("Izvoz")
```

**Comment by jasapozne** [comment]
Hvala, zdaj bi moralo vse delovati.

**Comment by katarinabrilej** [comment]
Ja, zdaj deluje uvoz. 

Samo v tabeli `uvoz.in.izvoz.Slovenija` raje zamenjaj ime prvega stolpca, da notri ne bo nastopal `/`, recimo `uvoz_ali_izvoz` ali kaj podobnega.
