### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by jaanos** [jasapozne/APPR-2020-21#2]
Opažam, da uvoz in risanje zemljevida opraviš kar v `uvozi.zemljevid.r`. Svetujem, da v tem programu pustiš samo definicijo funkcije `uvozi.zemljevid` (lahko jo [posodobiš](https://github.com/jasapozne/APPR-2020-21/compare/master...jaanos:zemljevid-kodiranje?expand=1)), samo klicanje funkcije in nadaljnje risanje pa raje opravi kje drugje, npr. v `vizualizacija.r`.

**Comment by jasapozne** [comment]
Sem popravil, hvala.
