### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by jasapozne** [jasapozne/APPR-2020-21#4]
Menim, da sem s projektom že pri koncu zato bi vas prosil, da ga pogledate in mi sporočite, če je kaj potrebno še spremeniti/dodati. Poleg tega me še zanima, kako bi lahko besedo _"Slovenia"_ v zadnjih grafih prestavil, da bi le-ta bila vidna v celoti. _hjust_ in _vjust_ mi namreč ne delujeta.

**Comment by katarinabrilej** [comment]
Oznake osi naj bodo usklajene med seboj, brez podčrtajev, s šumniki, enaka velikost črk. Enako velja za legende. Imena držav naj bodo raje v slovenščini. Vsi grafi naj imajo naslov. 

Pri zemljevidu ne potrebuješ legende za obrobe. Pri legendi saldo menjave pa lahko izpustiš številke spredaj (i), ii), ...)

Glede Shinyja: dobro bi bilo grafe razdeliti na različne zavihke in da bi bila možnost izbire parametra glede na katerega se potem izriše graf (torej da je input in output). 

V katerih grafih točno bi rad prestavil besedo Slovenia?

**Comment by jasapozne** [comment]
Popravil, hvala. Sem pa naknadno opazil, da se s spreminjanjem let, posodabljajo le grafi iz prvega zavihka, ostali ne, pa čeprav so vsi ti grafi podobno napisani.

**Comment by katarinabrilej** [comment]
Še v grafu `graf.drzav.izvoza` in `graf.drzav.uvoza` manjkajo šumniki v naslovu legend. In pri Sloveniji v legendi manjka j (trenutno je Slovenia). 

Pri grafu `napoved.za.uvoz` in `napoved.za.izvoz` bi na y osi lahko pisalo kaj bolj informativnega kot skupaj. 

Glede Shinyja: 

* še vedno bi bilo za popraviti oznake osi in legende. 
* namesto 
 ```
choices = c("2010", "2011", "2012","2013","2014","2015","2016","2017", "2018","2019")
```
lahko krajše zapišeš
```
choices = c(2010:2019)
```
* Pri `inputId` moraš za vsak zavihek ustvariti nov id, torej npr. leto1, leto2, ... namesto da so vsi leto. Tako se bodo spreminjali grafi na vseh zavihkih.

**Comment by jaanos** [comment]
Glede na to, da poročilo deluje, bom dodal povezavo do projekta na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

Naj opomnim, da mi poročilo včeraj ni prevedlo - problem je očitno bil sicer v tem, da je nekdo pobrisal tabelo BDP na prebivalca na Wikipediji. Upam sicer, da se to več ne bo zgodilo, ampak če bi bilo potrebno, bi lahko podatke pridobil iz katere od arhiviranih različic strani (na Wikipediji imaš zgoraj desno *View history*, potem pa klikneš na uro in datum želene različice). Seveda to tudi pomeni, da se bo vsakič uvozila ta različica - tudi, če se podatki posodobijo.

Poleg tega, na kar je zgoraj opozorila @katarinabrilej, imam še sledeče pripombe:
* Na več grafih se na osi y pojavijo oznake v eksponentni obliki. Da se jih znebiš, deli podatke z ustreznim številom (npr. za prvi graf lahko pri `aes` uporabiš parameter `y=SKUPEN_UVOZ/1e9`), poleg tega pa ustrezno popravi tudi oznake osi (za prejšnji primer naj bo torej iz oznake jasno, da gre za skupen uvoz v milijardah evrov).
* Legenda na zemljevidu salda je zelo nepregledna: težko je primerjati izpisane številke med seboj, poleg tega pa vrstni red ni konsistenten (najprej pozitivne vrednosti naraščajoče, nato negativne padajoče). Kolikor vidim, so te meje določene ročno - koristno bi bilo opisati, kako natančno so bile izbrane. Pravzaprav bi lahko celotno razvrščanje podatkov in izris zemljevida precej skrajšal, npr.
  ```R
  brks <- c(-320, -76, 0, 46, 150) # razmejitve med barvami
  rng <- range(izracun.salda$saldo_menjave/1e6)
  vals <- rescale(c(rng[1], brks, rng[2]))
  Zemljevid.Slovenskega.salda <- ggplot(left_join(zemljevid.2, izracun.salda,
                                                  by=c("drzava"="DRZAVA")),
                                        aes(x=long, y=lat, group=group, fill=saldo_menjave/1e6)) +
    geom_polygon() +
    scale_fill_stepsn(name="Saldo menjave Slovenije\ns tujino (mio €)",
                      breaks=brks, values=(vals[1:6] + vals[2:7])/2,
                      colours=c("#DE2D26", "#FC9272", "#FEE0D2", "#DEEBF7", "#9ECAE1", "#3182BD"),
                      na.value="orange", show.limits=TRUE,
                      labels=scales::label_number(accuracy=1, big.mark="")) +
    theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.text.y=element_blank(),
          axis.ticks.y=element_blank(), panel.background=element_rect(fill="dark gray"),
          plot.background=element_rect(fill="dark gray"), legend.key=element_rect(fill="dark gray"),
          legend.background=element_rect(fill="dark gray")) + 
    ggtitle("Slovenski saldo menjave s tujino za leto 2019") +
    labs(x="", y="")
  ```
* Pri prikazu aplikacije Shiny v poročilu povečaj parameter `height`, da se znebiš drsnika. Poskrbi tudi za naslove legend v grafih znotraj aplikacije.

**Comment by jasapozne** [comment]
Vse stvari sem sedaj popravil, zato bi prosil, da se povezava posodobi. Hkrati pa se zahvaljujem za vso pomoč.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
